name: Laravel CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Dependency
        run: composer install

      - name: Copy ENV
        run: cp .env.example .env

      - name: Generate Key
        run: php artisan key:generate
